name: Deploy Astro site to Pages

on:
  push:
    branches: ["master"]  # Trigger on pushes to master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  BUILD_PATH: "."

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"  # Use npm cache for dependency caching

      - name: Install dependencies
        run: npm install  # Explicitly run npm install
        working-directory: ${{ env.BUILD_PATH }}

      - name: Build with Astro
        run: npm run build  # Use npm to build your Astro site
        working-directory: ${{ env.BUILD_PATH }}

      - name: Debug build output
        run: ls -la ${{ env.BUILD_PATH }}/dist  # Check contents of the dist folder

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.BUILD_PATH }}/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Verify deployment URL
        run: echo "Deployed at ${{ steps.deployment.outputs.page_url }}"
